name: iOS Build & TestFlight

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      PROJECT_PATH: SumQuest
      BUILD_PATH: build/ios
      IOS_PROJECT_PATH: build/ios/iOS/SumQuest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Cache Unity Library
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ hashFiles('SumQuest/Assets/**','SumQuest/Packages/**','SumQuest/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # 3️⃣ Build Unity iOS project
      - name: Build Unity iOS Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: iOS
          buildName: SumQuest
          buildsPath: ${{ env.BUILD_PATH }}

      #- name: Show build structure
      #  run: ls -R ${{ env.BUILD_PATH }}

      # Set automatic build number
      - name: Set automatic build number
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          /usr/libexec/PlistBuddy \
            -c "Set :CFBundleVersion $BUILD_NUMBER" \
            ${{ env.IOS_PROJECT_PATH }}/Info.plist

      # Install distribution certificate
      - name: Install certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERT }}
          CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > cert.p12
          security create-keychain -p "" build.keychain
          security import cert.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain

      # Install provisioning profile
      - name: Install provisioning profile
        env:
          PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          echo "$PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(grep -a -E -o "UUID.*" profile.mobileprovision | head -1 | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

      - name: Check provisioning profile
        run: |
          security find-identity -v -p codesigning
          security cms -D -i profile.mobileprovision | grep -A2 "Name"
          security cms -D -i profile.mobileprovision | grep -A5 Entitlements

      # Build IPA using Xcode
      - name: Build IPA
        env:
          TEAM_ID: C677KJH544
        run: |
          cd ${{ env.IOS_PROJECT_PATH }}
         
          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build.xcarchive \
            -sdk iphoneos \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=com.taowang.sumquest \
            PROVISIONING_PROFILE_SPECIFIER=sumquest \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath build.xcarchive \
            -exportOptionsPlist ${{ github.workspace }}/SumQuest/ExportOptions.plist \
            -exportPath build

      # Upload to TestFlight
      - name: Upload to TestFlight
        env:
          APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: |
          IPA_PATH=$(find ${{ env.BUILD_PATH }} -name "*.ipa" | head -n 1)

          mkdir private_keys
          echo "$APPSTORE_API_KEY" > private_keys/AuthKey_${APPSTORE_API_KEY_ID}.p8

          xcrun altool \
            --upload-app \
            --type ios \
            --file "$IPA_PATH" \
            --apiKey $APPSTORE_API_KEY_ID \
            --apiIssuer $APPSTORE_ISSUER_ID

      # Return Unity license
      #- name: Return Unity License
      #  if: always()
      #  uses: game-ci/unity-return-license@v2
